# PlatformIO pre-build script: builds the GIFs that fit the panel into the
# firmware, for the clock's GIF playback.
#
# Sources: every .gif in gifs/ (the repository's examples, always taken) and in
# the folders listed in gif_dirs.local, one per line (git ignores that file, so
# private GIFs stay out of the repository). An exclude.txt in such a folder or
# its parent names files to leave out, one per line; a line matches the end of
# a file's path.
#
# A GIF fits when it is no larger than the panel either way round
# (custom_gif_panel, e.g. 64x32): the clock draws it centred and unscaled, in
# landscape or upright. GIFs from gif_dirs.local go in smallest first as long as
# custom_gif_budget_kb allows. The result is gif_library.h in the build folder:
# one array per GIF and the table BUILT_IN_GIFS.

import hashlib
import os

Import("env")  # noqa: F821 - provided by PlatformIO/SCons

PROJECT_DIR = env.subst("$PROJECT_DIR")
OUT_DIR = os.path.join(env.subst("$BUILD_DIR"), "gifgen")
OUT_FILE = os.path.join(OUT_DIR, "gif_library.h")


def gif_size(path):
    """(width, height) from the GIF header, or None if it is not a GIF."""
    with open(path, "rb") as f:
        head = f.read(10)
    if len(head) < 10 or head[:4] != b"GIF8":
        return None
    return head[6] | (head[7] << 8), head[8] | (head[9] << 8)


def gifs_in(folder):
    found = []
    for root, _dirs, files in os.walk(folder):
        for name in sorted(files):
            if name.lower().endswith(".gif"):
                found.append(os.path.join(root, name))
    return sorted(found)


def exclusions(folder):
    lines = []
    for where in (folder, os.path.dirname(os.path.abspath(folder))):
        path = os.path.join(where, "exclude.txt")
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as f:
                lines += [l.strip().replace("\\", "/") for l in f if l.strip() and not l.startswith("#")]
    return lines


def local_dirs():
    path = os.path.join(PROJECT_DIR, "gif_dirs.local")
    if not os.path.isfile(path):
        return []
    dirs = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                dirs.append(line if os.path.isabs(line) else os.path.join(PROJECT_DIR, line))
    return dirs


def c_name(stem, used):
    base = "".join(c if c.isalnum() else "_" for c in stem).strip("_") or "gif"
    name, n = base, 2
    while name in used:
        name, n = "%s_%d" % (base, n), n + 1
    used.add(name)
    return name


def build():
    panel = env.GetProjectOption("custom_gif_panel", "")
    if not panel:
        return
    pw, ph = (int(v) for v in panel.lower().split("x"))
    budget = int(env.GetProjectOption("custom_gif_budget_kb", "600")) * 1024

    def fits(size):
        w, h = size
        return (w <= pw and h <= ph) or (w <= ph and h <= pw)

    chosen, too_big, over_budget, seen = [], [], [], set()

    def take(path, size):
        with open(path, "rb") as f:
            data = f.read()
        digest = hashlib.sha1(data).hexdigest()
        if digest in seen:
            return 0
        seen.add(digest)
        chosen.append((path, size, data))
        return len(data)

    total = 0
    for path in gifs_in(os.path.join(PROJECT_DIR, "gifs")):
        size = gif_size(path)
        if size and fits(size):
            total += take(path, size)
        elif size:
            too_big.append(path)

    extra_dirs = [d for d in local_dirs() if os.path.isdir(d)]
    candidates = []
    for folder in extra_dirs:
        skip = exclusions(folder)
        for path in gifs_in(folder):
            rel = path.replace("\\", "/")
            if any(rel.endswith(s) for s in skip):
                continue
            size = gif_size(path)
            if size and fits(size):
                candidates.append((os.path.getsize(path), path, size))
            elif size:
                too_big.append(path)
    for nbytes, path, size in sorted(candidates):
        if total + nbytes > budget:
            over_budget.append(path)
            continue
        total += take(path, size)

    used, arrays, rows = set(), [], []
    for path, (w, h), data in chosen:
        name = c_name(os.path.splitext(os.path.basename(path))[0], used)
        body = ",\n".join("  " + ",".join("0x%02x" % b for b in data[i:i + 24]) for i in range(0, len(data), 24))
        arrays.append("static const uint8_t GIF_%s[] = {\n%s\n};" % (name.upper(), body))
        rows.append('  { "%s", %d, %d, GIF_%s, %d },' % (name, w, h, name.upper(), len(data)))
    if not rows:
        rows.append('  { "", 0, 0, nullptr, 0 },')

    text = "\n".join([
        "// Generated by scripts/embed_gifs.py - do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "struct BuiltInGif { const char *name; uint16_t width, height; const uint8_t *data; uint32_t size; };",
        "",
    ] + arrays + [
        "",
        "static const BuiltInGif BUILT_IN_GIFS[] = {",
    ] + rows + [
        "};",
        "static const uint16_t BUILT_IN_GIF_COUNT = %d;" % len(chosen),
        "",
    ])

    os.makedirs(OUT_DIR, exist_ok=True)
    old = open(OUT_FILE, encoding="utf-8").read() if os.path.isfile(OUT_FILE) else None
    if old != text:   # rewriting an unchanged file would rebuild the sketch every time
        with open(OUT_FILE, "w", encoding="utf-8") as f:
            f.write(text)

    print("GIFs: %d built in (%d KB) for a %dx%d panel; %d larger than the panel, %d over the %d KB budget"
          % (len(chosen), total // 1024, pw, ph, len(too_big), len(over_budget), budget // 1024))
    if extra_dirs:
        print("GIFs: including folders from gif_dirs.local (%s) - do not publish this firmware"
              % ", ".join(extra_dirs))


build()
env.Append(CPPPATH=[OUT_DIR])
