# PlatformIO pre-build script: builds the GIFs that fit the panel into the
# firmware, for the clock's GIF playback.
#
# Sources: every .gif in gifs/ (the repository's examples, always taken) and in
# the folders listed in gif_dirs.local, one per line (git ignores that file, so
# private GIFs stay out of the repository). An exclude.txt in such a folder or
# its parent names files to leave out, one per line; a line matches the end of
# a file's path.
#
# A GIF fits when it is no larger than the panel (custom_gif_panel, e.g. 64x32)
# the way the clock stands (custom_gif_orientation: landscape, the default,
# portrait or both, see gif_common.py): the clock draws it centred and
# unscaled. GIFs from gif_dirs.local go in smallest first as long as
# custom_gif_budget_kb allows. The result is gif_library.h in the build folder:
# one array per GIF and the table BUILT_IN_GIFS. The SHA-1s of the GIFs built
# in go to GIF_BUILT_IN_SHA1 in the build environment, so that the GIF pack
# (scripts/gif_pack.py) does not hold them twice.

import hashlib
import os
import sys

Import("env")  # noqa: F821 - provided by PlatformIO/SCons

PROJECT_DIR = env.subst("$PROJECT_DIR")
sys.path.insert(0, os.path.join(PROJECT_DIR, "scripts"))
import gif_common  # noqa: E402

OUT_DIR = os.path.join(env.subst("$BUILD_DIR"), "gifgen")
OUT_FILE = os.path.join(OUT_DIR, "gif_library.h")


def c_name(stem, used):
    base = "".join(c if c.isalnum() else "_" for c in stem).strip("_") or "gif"
    name, n = base, 2
    while name in used:
        name, n = "%s_%d" % (base, n), n + 1
    used.add(name)
    return name


def build():
    panel = env.GetProjectOption("custom_gif_panel", "")
    if not panel:
        return
    pw, ph = gif_common.panel_size(panel)
    orientation = gif_common.check_orientation(env.GetProjectOption("custom_gif_orientation", "landscape"))
    budget = int(env.GetProjectOption("custom_gif_budget_kb", "600")) * 1024

    def fits(size):
        return gif_common.fits(size, (pw, ph), orientation)

    chosen, too_big, over_budget, seen = [], [], [], set()

    def take(path, size):
        with open(path, "rb") as f:
            data = f.read()
        digest = hashlib.sha1(data).hexdigest()
        if digest in seen:
            return 0
        seen.add(digest)
        chosen.append((path, size, data))
        return len(data)

    total = 0
    for path in gif_common.gifs_in(os.path.join(PROJECT_DIR, "gifs")):
        size = gif_common.gif_size(path)
        if size and fits(size):
            total += take(path, size)
        elif size:
            too_big.append(path)

    extra_dirs = [d for d in gif_common.listed_dirs(PROJECT_DIR, "gif_dirs.local") if os.path.isdir(d)]
    candidates = []
    for folder in extra_dirs:
        skip = gif_common.exclusions(folder)
        for path in gif_common.gifs_in(folder):
            if gif_common.excluded(path, skip):
                continue
            size = gif_common.gif_size(path)
            if size and fits(size):
                candidates.append((os.path.getsize(path), path, size))
            elif size:
                too_big.append(path)
    for nbytes, path, size in sorted(candidates):
        if total + nbytes > budget:
            over_budget.append(path)
            continue
        total += take(path, size)

    used, arrays, rows = set(), [], []
    for path, (w, h), data in chosen:
        name = c_name(os.path.splitext(os.path.basename(path))[0], used)
        body = ",\n".join("  " + ",".join("0x%02x" % b for b in data[i:i + 24]) for i in range(0, len(data), 24))
        arrays.append("static const uint8_t GIF_%s[] = {\n%s\n};" % (name.upper(), body))
        rows.append('  { "%s", %d, %d, GIF_%s, %d },' % (name, w, h, name.upper(), len(data)))
    if not rows:
        rows.append('  { "", 0, 0, nullptr, 0 },')

    text = "\n".join([
        "// Generated by scripts/embed_gifs.py - do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "struct BuiltInGif { const char *name; uint16_t width, height; const uint8_t *data; uint32_t size; };",
        "",
    ] + arrays + [
        "",
        "static const BuiltInGif BUILT_IN_GIFS[] = {",
    ] + rows + [
        "};",
        "static const uint16_t BUILT_IN_GIF_COUNT = %d;" % len(chosen),
        "",
    ])

    os.makedirs(OUT_DIR, exist_ok=True)
    old = open(OUT_FILE, encoding="utf-8").read() if os.path.isfile(OUT_FILE) else None
    if old != text:   # rewriting an unchanged file would rebuild the sketch every time
        with open(OUT_FILE, "w", encoding="utf-8") as f:
            f.write(text)
    env["GIF_BUILT_IN_SHA1"] = " ".join(sorted(seen))

    print("GIFs: %d built in (%d KB) for a %dx%d panel standing %s; %d do not fit, %d over the %d KB budget"
          % (len(chosen), total // 1024, pw, ph, orientation, len(too_big), len(over_budget), budget // 1024))
    if extra_dirs:
        print("GIFs: including folders from gif_dirs.local (%s) - do not publish this firmware"
              % ", ".join(extra_dirs))


build()
env.Append(CPPPATH=[OUT_DIR])
