# PlatformIO pre-build script: builds the settings web app into the firmware.
#
# webui/index.html - one page with its CSS and script inline, no libraries and
# system fonts only, since the hotspot has no internet - is gzipped and written
# as the array WEBUI_GZ to webui_page.h in the build folder, which the sketch
# serves as it is (Content-Encoding: gzip). The header also carries
# FW_VERSION: the commit the build comes from (git describe, "-dirty" with
# changes not committed) and that commit's date. Only the sketch includes the
# header, so a new version rebuilds the sketch and nothing else.

import gzip
import os
import subprocess

Import("env")  # noqa: F821 - provided by PlatformIO/SCons

PROJECT_DIR = env.subst("$PROJECT_DIR")
SOURCE = os.path.join(PROJECT_DIR, "webui", "index.html")
OUT_DIR = os.path.join(env.subst("$BUILD_DIR"), "webgen")
OUT_FILE = os.path.join(OUT_DIR, "webui_page.h")


def git(*args):
    try:
        out = subprocess.run(["git", *args], cwd=PROJECT_DIR, capture_output=True, text=True, timeout=10)
        return out.stdout.strip() if out.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def build():
    with open(SOURCE, "rb") as f:
        page = f.read()
    # mtime=0: the same page gives the same bytes, so an unchanged page does
    # not change the header.
    packed = gzip.compress(page, compresslevel=9, mtime=0)
    version = git("describe", "--always", "--dirty", "--abbrev=7") or "unknown"
    date = git("log", "-1", "--format=%cd", "--date=short")
    if date:
        version += " " + date
    lines = [
        "// Generated by scripts/embed_webui.py from webui/index.html - do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        '#define FW_VERSION "%s"' % version.replace('"', ""),
        "const uint32_t WEBUI_GZ_LEN = %d;   // %d bytes before gzip" % (len(packed), len(page)),
        "const uint8_t WEBUI_GZ[] = {",
    ]
    for i in range(0, len(packed), 24):
        lines.append("  " + ",".join(str(b) for b in packed[i:i + 24]) + ",")
    lines.append("};")
    text = "\n".join(lines) + "\n"
    os.makedirs(OUT_DIR, exist_ok=True)
    old = None
    if os.path.exists(OUT_FILE):
        with open(OUT_FILE, encoding="utf-8") as f:
            old = f.read()
    if old != text:
        with open(OUT_FILE, "w", encoding="utf-8") as f:
            f.write(text)
    print("Web app: %d bytes, %d gzipped, firmware %s" % (len(page), len(packed), version))


build()
env.Append(CPPPATH=[OUT_DIR])
